
TOKENTABLE = [
    ( None,   r'[ \t\n]+'),
    ( None, r'#[^"]*#<!>'),
    ( 'FLOAT',  r'-?\d+\.\d+'),
    ( 'INTEGER',  r'-?\d+(?![.a-zA-Z])'),
    ( 'STRING',  r'"[^"]*"'),
    ( 'BOOL', r'true|false(?![a-zA-Z_])'),
    ( 'INT_TYPE', r'int(?![a-zA-Z_])'),
    ( 'FLOAT_TYPE', r'floa(?![a-zA-Z_])'),
    ( 'BOOL_TYPE', r'bool(?![a-zA-Z_])'),
    ( 'STRING_TYPE', r'string(?![a-zA-Z_])'),
    ( 'ARRAY_IDENTIFIER', r'[a-zA-Z_]\w*\[\]'),
    ( 'BASIC_MATH_OPERATOR',  r'[+\-*/]'),
    ( 'RELATION_OPERATOR', r'(==|!=|<=|>=|<|>)'),
    ( 'LOGIC_OPERATOR', r'(or|and|not)'),
    ( 'OPEN_PARAN', r'\('),
    ( 'CLOSE_PARAN', r'\)'),
    ( 'ATRIBUTION', r'\='),
    ( 'LINE_BREAK', r';'),
    ( 'FUNCTION', r'function(?![a-zA-Z_])'),
    ( 'ATRIBUTE_TYPE', r':'),
    ( 'FUNCTION_RETURN_TYPE', r'\-\>' ),
    ( 'OPEN_BRACE', r'{'),
    ( 'CLOSE_BRACE', r'}'),
    ( 'OPEN_BRACKET', r'\['),
    ( 'CLOSE_BRACKET', r'\]'),
    ( 'COMMA', r','),
    ( 'POINT', r'\.'),
    ( 'IF', r'if(?![a-zA-Z_])'),
    ( 'ELSE', r'else(?![a-zA-Z_])'),
    ( 'FOR', r'for(?![a-zA-Z_])'),
    ( 'WHILE', r'while(?![a-zA-Z_])'),
    ( 'STRUCT', r'struct(?![a-zA-Z_])'),
    ( 'INICIO', r'inicio(?![a-zA-Z_])'),
    ( 'COMPILADORES', r'compiladores(?![a-zA-Z_])'),
    ( 'IFSULDEMINAS', r'IFSULDEMINAS(?![a-zA-Z_])'),
    ( 'FIM', r'fim(?![a-zA-Z_])'),
    ( 'IDENTIFIER',  r'[a-zA-Z][a-zA-Z_1-9]*'),
]